# Generated by Django 5.2.16 on 2026-09-03 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_user_default_room_access_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakoutRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('name', models.CharField(help_text='User-visible room name, e.g. "Room 1".', max_length=200, verbose_name='display name')),
                ('livekit_room_name', models.CharField(help_text="The identifier used for the LiveKit room (prefixed with 'breakout_').", max_length=100, unique=True, verbose_name='LiveKit room name')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
            ],
            options={
                'verbose_name': 'Breakout Room',
                'verbose_name_plural': 'Breakout Rooms',
                'db_table': 'meet_breakout_room',
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='BreakoutAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('participant_identity', models.CharField(help_text='LiveKit identity (user.sub or stable anonymous UUID).', max_length=255, verbose_name='participant identity')),
                ('participant_name', models.CharField(blank=True, default='', help_text='Display name at the time of assignment.', max_length=255, verbose_name='participant display name')),
                ('breakout_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.breakoutroom', verbose_name='breakout room')),
            ],
            options={
                'verbose_name': 'Breakout Assignment',
                'verbose_name_plural': 'Breakout Assignments',
                'db_table': 'meet_breakout_assignment',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='BreakoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('status', models.CharField(choices=[('configuring', 'Configuring'), ('active', 'Active'), ('closed', 'Closed')], default='configuring', max_length=20, verbose_name='session status')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Optional timer duration. Participants are recalled when it expires.', null=True, verbose_name='duration in seconds')),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when the session was activated.', null=True, verbose_name='started at')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Timestamp when the session was closed.', null=True, verbose_name='closed at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_breakout_sessions', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('room', models.ForeignKey(help_text='The main meeting room this breakout session belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='breakout_sessions', to='core.room', verbose_name='parent room')),
            ],
            options={
                'verbose_name': 'Breakout Session',
                'verbose_name_plural': 'Breakout Sessions',
                'db_table': 'meet_breakout_session',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='breakoutroom',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakout_rooms', to='core.breakoutsession', verbose_name='breakout session'),
        ),
        migrations.AddConstraint(
            model_name='breakoutsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['configuring', 'active'])), fields=('room',), name='one_active_session_per_room'),
        ),
    ]
