# Generated by Django 5.2.16 on 2026-09-07 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_user_default_room_access_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('status', models.CharField(choices=[('configuring', 'Configuring'), ('activating', 'Activating'), ('active', 'Active'), ('closing', 'Closing'), ('closed', 'Closed')], default='configuring', max_length=20, verbose_name='session status')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Optional timer duration. Participants are recalled when it expires.', null=True, verbose_name='duration in seconds')),
                ('started_at', models.DateTimeField(blank=True, help_text='Timestamp when the session was activated.', null=True, verbose_name='started at')),
                ('ends_at', models.DateTimeField(blank=True, help_text='Absolute timer boundary for a timed breakout session.', null=True, verbose_name='ends at')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Timestamp when the session was closed.', null=True, verbose_name='closed at')),
                ('revision', models.PositiveBigIntegerField(default=0, help_text='Monotonic revision for participant-visible session changes.', verbose_name='revision')),
                ('effect_error', models.TextField(blank=True, default='', help_text='Latest retryable LiveKit reconciliation error.', verbose_name='effect error')),
                ('last_broadcast_message', models.CharField(blank=True, default='', help_text='Most recent host announcement, served through the assignment poll.', max_length=500, verbose_name='last broadcast message')),
                ('last_broadcast_at', models.DateTimeField(blank=True, null=True, verbose_name='last broadcast at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_breakout_sessions', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('room', models.ForeignKey(help_text='The main meeting room this breakout session belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='breakout_sessions', to='core.room', verbose_name='parent room')),
            ],
            options={
                'verbose_name': 'Breakout Session',
                'verbose_name_plural': 'Breakout Sessions',
                'db_table': 'meet_breakout_session',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BreakoutRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('name', models.CharField(help_text='User-visible room name, e.g. "Room 1".', max_length=200, verbose_name='display name')),
                ('livekit_room_name', models.CharField(help_text="The identifier used for the LiveKit room (prefixed with 'breakout_').", max_length=100, unique=True, verbose_name='LiveKit room name')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakout_rooms', to='core.breakoutsession', verbose_name='breakout session')),
            ],
            options={
                'verbose_name': 'Breakout Room',
                'verbose_name_plural': 'Breakout Rooms',
                'db_table': 'meet_breakout_room',
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='BreakoutHelpRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('requester_identity', models.CharField(db_index=True, max_length=255)),
                ('requester_name', models.CharField(blank=True, default='', max_length=255)),
                ('assignment_revision', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('cancelled', 'Cancelled'), ('acknowledged', 'Acknowledged')], default='open', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('breakout_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='core.breakoutroom', verbose_name='breakout room')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='core.breakoutsession', verbose_name='breakout session')),
            ],
            options={
                'db_table': 'meet_breakout_help_request',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='BreakoutAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('participant_identity', models.CharField(db_index=True, help_text='Server-issued LiveKit participant identity.', max_length=255, verbose_name='participant identity')),
                ('participant_name', models.CharField(blank=True, default='', help_text='Display name at the time of assignment.', max_length=255, verbose_name='participant display name')),
                ('breakout_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.breakoutroom', verbose_name='breakout room')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.breakoutsession', verbose_name='breakout session')),
            ],
            options={
                'verbose_name': 'Breakout Assignment',
                'verbose_name_plural': 'Breakout Assignments',
                'db_table': 'meet_breakout_assignment',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='breakoutsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['configuring', 'activating', 'active', 'closing'])), fields=('room',), name='one_active_session_per_room'),
        ),
        migrations.AddConstraint(
            model_name='breakouthelprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('session', 'requester_identity'), name='one_open_help_request_per_participant'),
        ),
        migrations.AddConstraint(
            model_name='breakoutassignment',
            constraint=models.UniqueConstraint(fields=('session', 'participant_identity'), name='one_breakout_assignment_per_participant'),
        ),
    ]
