# Generated by Django 5.2.16 on 2026-09-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_breakoutroom_breakoutassignment_breakoutsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakoutassignment',
            name='participant_identity',
            field=models.CharField(db_index=True, help_text='LiveKit identity (user.sub or stable anonymous UUID).', max_length=255, verbose_name='participant identity'),
        ),
    ]
